language: cpp

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: osx
    - os: windows

before_script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTING=On

script: make && make test

