language: cpp

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: osx
      osx_image: xcode11.3
    - os: windows

before_script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTING=On -GNinja

script: ninja && ninja test

