language: cpp

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: osx
      osx_image: xcode11.3
    - os: windows

before_script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTING=On 

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make && make test ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make && make test ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then nmake && nmake test ; fi
